### ISSUE TITLE
unplugin docs

### ISSUE THREAD

**Issue by yuyinws** [yuyinws/unplugin-docs#1]
Hi! @sxzz @antfu 

The [docs website](https://unplugin.vercel.app) for unplugin has been basically completed. 

Please check if there is any content that needs to be modified. Or what suggestions do you have for this website?

**Comment by antfu** [comment]
Nice work!
I wonder if we could pull the readme of each official repo to render in the docs as well?

**Comment by yuyinws** [comment]
Yes, we can do it with GitHub GraphQL API.


<img width="1388" alt="image" src="https://github.com/unplugin/docs/assets/38490578/846d2517-a361-4af6-88d9-d369179083e9">


But render all the readme content on `showcase` will let this page too large, do you have better UI/UX suggestion?

**Comment by yuyinws** [comment]
Hi, @antfu 
I refactored the [showcase page](https://unplugin.vercel.app/showcase/), and now all the repos have their readme page. 

All the repositories that need to be displayed are defined in [this file](https://github.com/unplugin/docs/blob/main/.vitepress/data/meta.ts).

When running `pnpm gen-files`, the script will fetch the latest repo information and generate markdown file automatically.

---

But there is still one question:
The Markdown syntax of Vitepress is more strict than GitHub. For example, The following syntaxes all cause compilation errors in Vitepress:

### error 1

https://github.com/unplugin/unplugin-vue-components/blob/aeaf51d422da1286a204581ebd9d11d5e8c0361f/README.md?plain=1#L66

![image](https://github.com/unplugin/docs/assets/38490578/709f7b5b-f3d8-42a3-8042-def9eb0ade80)

### error 2

https://github.com/unplugin/unplugin-icons/blob/main/README.md?plain=1#L425

![image](https://github.com/unplugin/docs/assets/38490578/90baffb4-6eec-46fd-8457-ad46d7e5290a)

### error 3

https://github.com/unplugin/unplugin-vue-cssvars/blob/master/README.md?plain=1#L139

<img width="661" alt="image" src="https://github.com/unplugin/docs/assets/38490578/714b6dd6-2741-44af-8734-9ea984038c0a">

Now I have manually handled these errors. 
https://github.com/unplugin/docs/blob/c47da43fe9de30a9f315e687a693aec2a34dbfb5/.vitepress/data/patch.ts#L1-L10

This is not a universal solution. And in the future, We may encounter new errors.

I try to use [nuxt/docus](https://github.com/nuxt-themes/docus) instead of Vitepress,  **error2**, and **error 3**  did not appear in docus. Maybe we should Migrate to docus？

What do you think about it？🤔

**Comment by Barbapapazes** [comment]
Hello,

Do not use nuxt/docus, it's deprecated.

**Comment by Barbapapazes** [comment]
For the UnJS website, we also pull readme from GitHub and I parse it using nuxt/content.

https://github.com/unjs/website/blob/main/server/api/github/%5Bowner%5D/%5Brepo%5D/readme.ts#L9

**Comment by yuyinws** [comment]
> For the UnJS website, we also pull readme from GitHub and I parse it using nuxt/content.
> 
> [unjs/website@`main`/server/api/github/%5Bowner%5D/%5Brepo%5D/readme.ts#L9](https://github.com/unjs/website/blob/main/server/api/github/%5Bowner%5D/%5Brepo%5D/readme.ts?rgh-link-date=2023-12-20T14%3A38%3A43Z#L9)

Thanks for replying! This is very helpful🥳

**Comment by yuyinws** [comment]
@antfu Hi, I think the docs are ready to ship! 
WDYT👀?

**Comment by antfu** [comment]
Made some suggestions here #2
