### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by antfu** [yuyinws/unplugin-docs#2]
1. For guides, I don't feel it's worth it to separate each section into multiple pages, as they are not that long for each. Doing so make it hard to read as extra clicks are required. I think we could have:
  - Guide > Get Started (The current readme, merge all sections)
  - Guide > Why Unplugin (I can write it later)
  - Guide > Plugin Conventions
3. We could unified the case `Unplugin`
4. For the Hero page:
  - We could use Icons of supported bundlers as features, similar to https://vitepress.dev/
  - We could remove the growing effect, and make the logo color-mode aware
  - We don't need the sponsors section
  - The footer should be `UnJS Team` instead of `Nuxt Contrib`
5. For community showcases, we could say something like: "Here are a few unplugins maintained by the unplugin team, find more on npm: https://www.npmjs.com/search?q=keywords%3Aunplugin"

**Comment by yuyinws** [comment]
I have made changes to the website according to your suggestion. 

You can write `Why Unplugin` section [here](https://github.com/unplugin/docs/blob/main/guide/why-unplugin.md).

**Comment by antfu** [comment]
Thanks!
