### ISSUE TITLE
Move Docs to unplugin repo

### ISSUE THREAD

**Issue by sxzz** [yuyinws/unplugin-docs#7]
The code and docs of unplugin should be in the same repo. Let's merge this repo to https://github.com/unjs/unplugin

**Comment by yuyinws** [comment]
Sounds good. I will start it recently. 

BTW, current the website's Vercel project is link to my [fork](https://github.com/yuyinws/unplugin-docs).
(Vercel’s personal account does not have permission to connect to an organization’s repo.)

Therefore, the build of Vercel will be triggered only when my fork is updated.It should be fixed as well.

**Comment by sxzz** [comment]
1. Build on GitHub Action
2. We can use this action to upload dist to Vercel, even a personal account.
   https://github.com/marketplace/actions/vercel-action#github-actions

**Comment by sxzz** [comment]
@yuyinws Please update the docs when you have a moment.

**Comment by yuyinws** [comment]
> @yuyinws Please update the docs when you have a moment.

Sure. Already working on it. I will send a PR to unplguin tomorrow.
